condition(hipertension)
condition(arritmias)
condition(insuficiencia_cardiaca)
condition(antecedentes_infarto)
condition(acv)
condition(enfermedad_renal_cronica)
condition(insuficiencia_renal)
condition(calculos_renales)
condition(higado_graso)
condition(cirrosis)
condition(hepatitis_cronica)
condition(diabetes)
condition(hipotiroidismo)
condition(hipertiroidismo)
condition(dislipidemia)
condition(asma)
condition(epoc)
condition(apnea_del_sueno)
condition(ulceras_gastricas)
condition(ulceras)
condition(erge)
condition(enfermedad_crohn)
condition(colitis_ulcerosa)
condition(epilepsia)
condition(depresion)
condition(trastorno_bipolar)
condition(parkinson)
condition(alzheimer)
condition(demencia)
condition(lupus)
condition(artritis_reumatoide)
condition(vih)
condition(cancer)
condition(glaucoma)
condition(hiperplasia_prostatica_benigna)
condition(trastornos_coagulacion)
condition(hemofilia)
condition(embarazo)
condition(lactancia_materna)

medicamento(paracetamol)
medicamento(ibuprofeno)
medicamento(omeprazol)
medicamento(amoxicilina)
medicamento(losartan)
medicamento(metformina)
medicamento(salbutamol)
medicamento(loratadina)
medicamento(atorvastatina)
medicamento(levotiroxina)
medicamento(enalapril)
medicamento(clonazepam)
medicamento(sertralina)
medicamento(ciprofloxacino)
medicamento(naproxeno)
medicamento(aspirina)
medicamento(ketorolaco)
medicamento(amlodipino)
medicamento(metoprolol)
medicamento(metoclopramida)
medicamento(hidroclorotiazida)
medicamento(tramadol)
medicamento(prednisona)
medicamento(alprazolam)
medicamento(furosemida)
medicamento(glibenclamida)
medicamento(azitromicina)
medicamento(clorfenamina)
medicamento(butilhioscina)
medicamento(tamsulosina)
medicamento(montelukast)
medicamento(simvastatina)
medicamento(fluconazol)
medicamento(sildenafilo)
medicamento(dexketoprofeno)


ataca(paracetamol, dolor_leve_moderado)
ataca(paracetamol, fiebre)
ataca(ibuprofeno, dolor)
ataca(ibuprofeno, inflamacion)
ataca(ibuprofeno, fiebre)
ataca(omeprazol, acidez)
ataca(omeprazol, reflujo_gastrico)
ataca(omeprazol, gastritis)
ataca(amoxicilina, infecciones_bacterianas)
ataca(losartan, hipertension_arterial)
ataca(metformina, nivel_alto_azucar)
ataca(salbutamol, broncoespasmo)
ataca(salbutamol, sibilancias)
ataca(salbutamol, falta_aire)
ataca(loratadina, alergias)
ataca(loratadina, rinitis)
ataca(loratadina, picazon)
ataca(loratadina, urticaria)
ataca(atorvastatina, colesterol_elevado)
ataca(levotiroxina, hipotiroidismo)
ataca(levotiroxina, fatiga)
ataca(levotiroxina, peso)
ataca(enalapril, hipertension)
ataca(enalapril, insuficiencia_cardiaca)
ataca(clonazepam, ansiedad_severa)
ataca(clonazepam, panico)
ataca(clonazepam, convulsiones)
ataca(sertralina, depresion)
ataca(sertralina, panico)
ataca(sertralina, ansiedad)
ataca(sertralina, toc)
ataca(ciprofloxacino, infecciones_bacterianas_complejas)
ataca(naproxeno, dolor_articular)
ataca(naproxeno, dolor_muscular)
ataca(naproxeno, inflamacion)
ataca(aspirina, dolor_leve)
ataca(aspirina, fiebre)
ataca(aspirina, riesgo_trombos)
ataca(ketorolaco, dolor_agudo_moderado)
ataca(ketorolaco, dolor_severo)
ataca(amlodipino, hipertension_arterial)
ataca(amlodipino, angina_pecho)
ataca(metoprolol, hipertension)
ataca(metoprolol, arritmias)
ataca(metoprolol, angina)
ataca(metoclopramida, nauseas)
ataca(metoclopramida, vomitos)
ataca(metoclopramida, vaciado_gastrico_lento)
ataca(hidroclorotiazida, hipertension)
ataca(hidroclorotiazida, retencion_liquidos)
ataca(tramadol, dolor_moderado)
ataca(tramadol, dolor_severo)
ataca(prednisona, inflamacion_severa)
ataca(prednisona, reacciones_autoinmunes)
ataca(alprazolam, crisis_ansiedad)
ataca(alprazolam, panico)
ataca(furosemida, edema)
ataca(furosemida, insuficiencia_cardiaca)
ataca(glibenclamida, azucar_alta)
ataca(azitromicina, infecciones_respiratorias)
ataca(azitromicina, infecciones_piel)
ataca(clorfenamina, sintomas_alergicos)
ataca(clorfenamina, estornudos)
ataca(clorfenamina, congestion)
ataca(butilhioscina, colicos_abdominales)
ataca(butilhioscina, espasmos_digestivos)
ataca(tamsulosina, dificultad_orinar)
ataca(montelukast, prevencion_asma)
ataca(montelukast, rinitis_alergica)
ataca(simvastatina, colesterol_alto)
ataca(simvastatina, trigliceridos)
ataca(fluconazol, infecciones_hongos)
ataca(sildenafilo, disfuncion_erectil)
ataca(sildenafilo, hipertension_pulmonar)
ataca(dexketoprofeno, dolor_agudo_dental)
ataca(dexketoprofeno, dolor_agudo_muscular)
ataca(dexketoprofeno, dolor_agudo_menstrual)

contraindicacion(paracetamol, cirrosis)
contraindicacion(paracetamol, higado_graso_severo)
contraindicacion(paracetamol, hepatitis_cronica)
contraindicacion(paracetamol, insuficiencia_renal_grave)
contraindicacion(ibuprofeno, ulceras)
contraindicacion(ibuprofeno, erge)
contraindicacion(ibuprofeno, crohn)
contraindicacion(ibuprofeno, colitis)
contraindicacion(ibuprofeno, enfermedad_renal)
contraindicacion(ibuprofeno, insuficiencia_renal)
contraindicacion(ibuprofeno, hipertension)
contraindicacion(ibuprofeno, insuficiencia_cardiaca)
contraindicacion(ibuprofeno, infarto)
contraindicacion(ibuprofeno, acv)
contraindicacion(ibuprofeno, hemofilia)
contraindicacion(ibuprofeno, embarazo)
contraindicacion(omeprazol, vih)
contraindicacion(omeprazol, sida)
contraindicacion(omeprazol, embarazo)
contraindicacion(omeprazol, lactancia_materna)
contraindicacion(amoxicilina, insuficiencia_renal_grave)
contraindicacion(amoxicilina, cirrosis)
contraindicacion(amoxicilina, hepatitis)
contraindicacion(losartan, embarazo_activo)
contraindicacion(losartan, lactancia_materna)
contraindicacion(losartan, insuficiencia_renal_grave)
contraindicacion(metformina, insuficiencia_renal)
contraindicacion(metformina, cirrosis)
contraindicacion(metformina, higado_graso_grave)
contraindicacion(metformina, insuficiencia_cardiaca)
contraindicacion(metformina, epoc_severa)
contraindicacion(salbutamol, arritmias)
contraindicacion(salbutamol, hipertiroidismo)
contraindicacion(salbutamol, insuficiencia_cardiaca_no_controlada)
contraindicacion(loratadina, cirrosis)
contraindicacion(loratadina, insuficiencia_hepatica_grave)
contraindicacion(loratadina, glaucoma)
contraindicacion(atorvastatina, cirrosis)
contraindicacion(atorvastatina, hepatitis_activa)
contraindicacion(atorvastatina, higado_graso_severo)
contraindicacion(atorvastatina, embarazo)
contraindicacion(atorvastatina, lactancia_materna)
contraindicacion(levotiroxina, hipertiroidismo)
contraindicacion(levotiroxina, infarto_reciente)
contraindicacion(levotiroxina, cardiopatia_activa)
contraindicacion(enalapril, embarazo_activo)
contraindicacion(enalapril, lactancia_materna)
contraindicacion(enalapril, insuficiencia_renal_grave)
contraindicacion(clonazepam, apnea_del_sueno)
contraindicacion(clonazepam, epoc)
contraindicacion(clonazepam, respiratorio_grave)
contraindicacion(clonazepam, glaucoma)
contraindicacion(clonazepam, cirrosis)
contraindicacion(clonazepam, embarazo)
contraindicacion(clonazepam, lactancia_materna)
contraindicacion(sertralina, trastorno_bipolar)
contraindicacion(sertralina, epilepsia_no_controlada)
contraindicacion(sertralina, hemofilia)
contraindicacion(sertralina, cirrosis)
contraindicacion(ciprofloxacino, arritmias)
contraindicacion(ciprofloxacino, epilepsia)
contraindicacion(ciprofloxacino, lupus)
contraindicacion(ciprofloxacino, artritis)
contraindicacion(ciprofloxacino, embarazo)
contraindicacion(ciprofloxacino, lactancia_materna)
contraindicacion(naproxeno, ulceras)
contraindicacion(naproxeno, colitis)
contraindicacion(naproxeno, crohn)
contraindicacion(naproxeno, insuficiencia_renal)
contraindicacion(naproxeno, hipertension)
contraindicacion(naproxeno, hemofilia)
contraindicacion(naproxeno, embarazo)
contraindicacion(aspirina, ulceras)
contraindicacion(aspirina, hemofilia)
contraindicacion(aspirina, asma)
contraindicacion(aspirina, insuficiencia_renal_grave)
contraindicacion(aspirina, insuficiencia_hepatica_grave)
contraindicacion(aspirina, embarazo)
contraindicacion(ketorolaco, ulceras)
contraindicacion(ketorolaco, erge)
contraindicacion(ketorolaco, colitis)
contraindicacion(ketorolaco, insuficiencia_renal)
contraindicacion(ketorolaco, hemofilia)
contraindicacion(ketorolaco, infarto)
contraindicacion(ketorolaco, acv)
contraindicacion(ketorolaco, embarazo)
contraindicacion(amlodipino, insuficiencia_cardiaca_severa)
contraindicacion(amlodipino, cirrosis)
contraindicacion(amlodipino, insuficiencia_hepatica)
contraindicacion(amlodipino, embarazo)
contraindicacion(metoprolol, asma)
contraindicacion(metoprolol, epoc)
contraindicacion(metoprolol, arritmias_bradicardicas)
contraindicacion(metoprolol, insuficiencia_cardiaca_descompensada)
contraindicacion(metoclopramida, parkinson)
contraindicacion(metoclopramida, epilepsia)
contraindicacion(metoclopramida, ulceras_sangrado_activo)
contraindicacion(metoclopramida, ulceras_perforacion)
contraindicacion(hidroclorotiazida, insuficiencia_renal)
contraindicacion(hidroclorotiazida, anuria)
contraindicacion(hidroclorotiazida, calculos_renales)
contraindicacion(hidroclorotiazida, gota)
contraindicacion(hidroclorotiazida, cirrosis)
contraindicacion(hidroclorotiazida, diabetes)
contraindicacion(tramadol, epilepsia)
contraindicacion(tramadol, apnea_del_sueno)
contraindicacion(tramadol, epoc)
contraindicacion(tramadol, cirrosis)
contraindicacion(tramadol, depresion_tratada_isrs)
contraindicacion(prednisona, diabetes)
contraindicacion(prednisona, hipertension)
contraindicacion(prednisona, ulceras)
contraindicacion(prednisona, glaucoma)
contraindicacion(prednisona, vih)
contraindicacion(prednisona, cancer)
contraindicacion(prednisona, infeccion_activa)
contraindicacion(alprazolam, apnea_del_sueno)
contraindicacion(alprazolam, epoc)
contraindicacion(alprazolam, glaucoma)
contraindicacion(alprazolam, cirrosis)
contraindicacion(alprazolam, embarazo)
contraindicacion(furosemida, insuficiencia_renal_anurica)
contraindicacion(furosemida, cirrosis)
contraindicacion(furosemida, encefalopatia)
contraindicacion(furosemida, calculos_renales)
contraindicacion(glibenclamida, diabetes_tipo_1)
contraindicacion(glibenclamida, insuficiencia_renal)
contraindicacion(glibenclamida, cirrosis)
contraindicacion(glibenclamida, insuficiencia_hepatica)
contraindicacion(glibenclamida, embarazo)
contraindicacion(azitromicina, arritmias)
contraindicacion(azitromicina, prolongacion_intervalo_qt)
contraindicacion(azitromicina, cirrosis)
contraindicacion(azitromicina, hepatitis_grave)
contraindicacion(clorfenamina, glaucoma)
contraindicacion(clorfenamina, hiperplasia_prostatica_benigna)
contraindicacion(clorfenamina, asma)
contraindicacion(clorfenamina, epoc)
contraindicacion(butilhioscina, glaucoma)
contraindicacion(butilhioscina, hiperplasia_prostatica_benigna)
contraindicacion(butilhioscina, arritmias)
contraindicacion(butilhioscina, taquicardia)
contraindicacion(tamsulosina, cirrosis)
contraindicacion(tamsulosina, insuficiencia_hepatica_grave)
contraindicacion(tamsulosina, glaucoma)
contraindicacion(tamsulosina, sindrome_iris_flacido)
contraindicacion(montelukast, depresion)
contraindicacion(montelukast, trastornos_estado_animo)
contraindicacion(montelukast, cirrosis)
contraindicacion(simvastatina, cirrosis)
contraindicacion(simvastatina, hepatitis_activa)
contraindicacion(simvastatina, higado_graso)
contraindicacion(simvastatina, embarazo)
contraindicacion(simvastatina, lactancia_materna)
contraindicacion(fluconazol, arritmias)
contraindicacion(fluconazol, cirrosis)
contraindicacion(fluconazol, insuficiencia_hepatica_grave)
contraindicacion(fluconazol, embarazo)
contraindicacion(sildenafilo, infarto_reciente)
contraindicacion(sildenafilo, acv_reciente)
contraindicacion(sildenafilo, insuficiencia_cardiaca)
contraindicacion(sildenafilo, arritmias)
contraindicacion(sildenafilo, hipertension)
contraindicacion(dexketoprofeno, ulceras)
contraindicacion(dexketoprofeno, crohn)
contraindicacion(dexketoprofeno, colitis)
contraindicacion(dexketoprofeno, insuficiencia_renal)
contraindicacion(dexketoprofeno, insuficiencia_hepatica)
contraindicacion(dexketoprofeno, hemofilia)
contraindicacion(dexketoprofeno, asma)
contraindicacion(dexketoprofeno, embarazo)
