condition(hipertension)
condition(arritmias)
condition(insuficiencia_cardiaca)
condition(antecedentes_infarto)
condition(acv)
condition(enfermedad_renal_cronica)
condition(insuficiencia_renal)
condition(calculos_renales)
condition(higado_graso)
condition(cirrosis)
condition(hepatitis_cronica)
condition(diabetes)
condition(hipotiroidismo)
condition(hipertiroidismo)
condition(dislipidemia)
condition(asma)
condition(epoc)
condition(apnea_del_sueno)
condition(ulceras_gastricas)
condition(ulceras)
condition(erge)
condition(enfermedad_crohn)
condition(colitis_ulcerosa)
condition(epilepsia)
condition(depresion)
condition(trastorno_bipolar)
condition(parkinson)
condition(alzheimer)
condition(demencia)
condition(lupus)
condition(artritis_reumatoide)
condition(vih)
condition(cancer)
condition(glaucoma)
condition(hiperplasia_prostatica_benigna)
condition(trastornos_coagulacion)
condition(hemofilia)
condition(embarazo)
condition(lactancia_materna)

medicamento(paracetamol)
medicamento(ibuprofeno)
medicamento(omeprazol)
medicamento(amoxicilina)
medicamento(losartan)
medicamento(metformina)
medicamento(salbutamol)
medicamento(loratadina)
medicamento(atorvastatina)
medicamento(levotiroxina)
medicamento(enalapril)
medicamento(clonazepam)
medicamento(sertralina)
medicamento(ciprofloxacino)
medicamento(naproxeno)
medicamento(aspirina)
medicamento(ketorolaco)
medicamento(amlodipino)
medicamento(metoprolol)
medicamento(metoclopramida)
medicamento(hidroclorotiazida)
medicamento(tramadol)
medicamento(prednisona)
medicamento(alprazolam)
medicamento(furosemida)
medicamento(glibenclamida)
medicamento(azitromicina)
medicamento(clorfenamina)
medicamento(butilhioscina)
medicamento(tamsulosina)
medicamento(montelukast)
medicamento(simvastatina)
medicamento(fluconazol)
medicamento(sildenafilo)
medicamento(dexketoprofeno)


ataca(paracetamol, dolor_leve_moderado)
ataca(paracetamol, fiebre)
ataca(ibuprofeno, dolor)
ataca(ibuprofeno, inflamacion)
ataca(ibuprofeno, fiebre)
ataca(omeprazol, acidez)
ataca(omeprazol, reflujo_gastrico)
ataca(omeprazol, gastritis)
ataca(amoxicilina, infecciones_bacterianas)
ataca(losartan, hipertension_arterial)
ataca(metformina, nivel_alto_azucar)
ataca(salbutamol, broncoespasmo)
ataca(salbutamol, sibilancias)
ataca(salbutamol, falta_aire)
ataca(loratadina, alergias)
ataca(loratadina, rinitis)
ataca(loratadina, picazon)
ataca(loratadina, urticaria)
ataca(atorvastatina, colesterol_elevado)
ataca(levotiroxina, hipotiroidismo)
ataca(levotiroxina, fatiga)
ataca(levotiroxina, peso)
ataca(enalapril, hipertension)
ataca(enalapril, insuficiencia_cardiaca)
ataca(clonazepam, ansiedad_severa)
ataca(clonazepam, panico)
ataca(clonazepam, convulsiones)
ataca(sertralina, depresion)
ataca(sertralina, panico)
ataca(sertralina, ansiedad)
ataca(sertralina, toc)
ataca(ciprofloxacino, infecciones_bacterianas_complejas)
ataca(naproxeno, dolor_articular)
ataca(naproxeno, dolor_muscular)
ataca(naproxeno, inflamacion)
ataca(aspirina, dolor_leve)
ataca(aspirina, fiebre)
ataca(aspirina, riesgo_trombos)
ataca(ketorolaco, dolor_agudo_moderado)
ataca(ketorolaco, dolor_severo)
ataca(amlodipino, hipertension_arterial)
ataca(amlodipino, angina_pecho)
ataca(metoprolol, hipertension)
ataca(metoprolol, arritmias)
ataca(metoprolol, angina)
ataca(metoclopramida, nauseas)
ataca(metoclopramida, vomitos)
ataca(metoclopramida, vaciado_gastrico_lento)
ataca(hidroclorotiazida, hipertension)
ataca(hidroclorotiazida, retencion_liquidos)
ataca(tramadol, dolor_moderado)
ataca(tramadol, dolor_severo)
ataca(prednisona, inflamacion_severa)
ataca(prednisona, reacciones_autoinmunes)
ataca(alprazolam, crisis_ansiedad)
ataca(alprazolam, panico)
ataca(furosemida, edema)
ataca(furosemida, insuficiencia_cardiaca)
ataca(glibenclamida, azucar_alta)
ataca(azitromicina, infecciones_respiratorias)
ataca(azitromicina, infecciones_piel)
ataca(clorfenamina, sintomas_alergicos)
ataca(clorfenamina, estornudos)
ataca(clorfenamina, congestion)
ataca(butilhioscina, colicos_abdominales)
ataca(butilhioscina, espasmos_digestivos)
ataca(tamsulosina, dificultad_orinar)
ataca(montelukast, prevencion_asma)
ataca(montelukast, rinitis_alergica)
ataca(simvastatina, colesterol_alto)
ataca(simvastatina, trigliceridos)
ataca(fluconazol, infecciones_hongos)
ataca(sildenafilo, disfuncion_erectil)
ataca(sildenafilo, hipertension_pulmonar)
ataca(dexketoprofeno, dolor_agudo_dental)
ataca(dexketoprofeno, dolor_agudo_muscular)
ataca(dexketoprofeno, dolor_agudo_menstrual)
